language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt -q
  - pip install -r test-requirements.txt -q
# command to run tests
script:
  - pytest tests/
